# If true, then the Aerial Affinity enchantment will be registered and the tag for it will
# function.
addAerialAffinity = true

# If true, then the default tag enchantment effect interceptor will be registered for allowing
# tagged status effects to simulate enchantment. Changing this setting requires a game reload.
addTagEnchantmentInterceptor = true

# The number of ticks for the Sniffer's cooldown. The default vanilla value is 9600.
snifferCooldown = 9600

# If True, Peaceful mode will be enforced. The player will not be able to change difficulty in any
# form.
forcePeaceful = true

[portalFormation]
# If true, enables the height-based Nether Portal interceptor. This ain't for you.
enableHeightBasedInterceptor = false

maxPortalWorldHeight = -1000
minPortalWorldHeight = -1030